modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
issueTrackerURL="https://github.com/Team-Fruit/SaveTools/issues"

[[mods]]
modId="savetools"
version="${file.jarVersion}"
displayName="SaveTools"
displayURL="https://www.teamfruit.net/"
authors="sjcl"
description='''
This mod protects your preciousfully tools/weapons from breaking via over use!!
'''

[[dependencies.savetools]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.savetools]] #optional
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.savetools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="CLIENT"